name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: | 
        dotnet restore BookingApp.Rooms/BookingApp.Rooms.sln
        dotnet restore BookingApp.Users/BookingApp.Users.sln
    - name: Build
      run: |         
        dotnet build --no-restore BookingApp.Rooms/BookingApp.Rooms.sln
        dotnet build --no-restore BookingApp.Users/BookingApp.Users.sln
